### ISSUE TITLE
imagereadme

### ISSUE THREAD

**Issue by QGoGithub** [Hexal7785/Merton-Jump-Diffusion-CPP#1]
![image](https://user-images.githubusercontent.com/8112239/33166918-cb8f923e-d033-11e7-9569-49bbadf2725a.png)

**Comment by Hexal7785** [comment]
![33166918-cb8f923e-d033-11e7-9569-49bbadf2725a](https://user-images.githubusercontent.com/8112239/33167037-317b66ea-d034-11e7-842c-9e70bc676132.png)
